"""Static shell-completion scripts emitted by ``--completion``.

Hand-written rather than autogenerated, so the per-flag tailoring (file
paths for ``--config``, env-var names for ``--imap-password-env``,
choice enumeration for ``--imap-tls``, modifier discovery in the
pattern argument) can be richer than what argparse introspection gives.

A drift test in ``tests/test_completions.py`` asserts that every flag
listed by the argparse parser appears in each shell's completion
script, so it's hard to forget to update one of them when adding a flag.
"""

from __future__ import annotations

ZSH = r"""#compdef muttlike-imap
# Zsh completion for muttlike-imap.
#
# To install, either:
#   - eval "$(muttlike-imap --completion zsh)"   in your ~/.zshrc, or
#   - save this file as _muttlike-imap somewhere on your $fpath.

_muttlike-imap() {
    _arguments -s -S \
        '--limit[Maximum number of results (default 10)]:limit:' \
        '--mailbox[IMAP folder to search (default INBOX)]:mailbox:_muttlike-imap-mailboxes' \
        '--summary[Human-readable output instead of JSON]' \
        '--body[Include full body text in output]' \
        '*--uid[Fetch specific messages by UID instead of searching]:uid:' \
        '--list-mailboxes[List available IMAP folders and exit]' \
        '--me[Email address used by ~p / ~P]:email:' \
        '--imap-host[IMAP server host]:host:_hosts' \
        '--imap-port[IMAP server port (default 993)]:port:' \
        '--imap-user[IMAP username]:user:' \
        '--imap-password-env[Read password from this env var]:envvar:_vars' \
        '--imap-password-cmd[Shell command that prints the password]:command:' \
        '--imap-tls[Use TLS (default true)]:bool:(true false)' \
        '--config[Path to a config file]:config file:_files' \
        '--timeout[Socket timeout in seconds]:seconds:' \
        '--completion[Print a shell completion script]:shell:(bash zsh fish)' \
        '--version[Show version and exit]' \
        '(--help -h)'{--help,-h}'[Show help and exit]' \
        '*:pattern:'
}

_muttlike-imap-mailboxes() {
    local -a mailboxes
    mailboxes=("${(@f)$(muttlike-imap --list-mailboxes 2>/dev/null)}")
    _values 'mailbox' $mailboxes
}

# Register the completion. Idempotent if already registered (e.g. via
# autoload from $fpath, in which case the #compdef directive above
# handled it).
compdef _muttlike-imap muttlike-imap
"""

BASH = r"""# Bash completion for muttlike-imap.
# Install via:  eval "$(muttlike-imap --completion bash)"

_muttlike_imap() {
    local cur prev opts
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    opts="--limit --mailbox --summary --body --uid --list-mailboxes --me \
          --imap-host --imap-port --imap-user --imap-password-env \
          --imap-password-cmd --imap-tls --config --timeout \
          --completion --version --help"

    case "${prev}" in
        --imap-tls)
            COMPREPLY=( $(compgen -W "true false" -- "${cur}") )
            return 0
            ;;
        --completion)
            COMPREPLY=( $(compgen -W "bash zsh fish" -- "${cur}") )
            return 0
            ;;
        --config)
            COMPREPLY=( $(compgen -f -- "${cur}") )
            return 0
            ;;
        --imap-password-env)
            COMPREPLY=( $(compgen -A variable -- "${cur}") )
            return 0
            ;;
    esac

    if [[ ${cur} == --* ]]; then
        COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
        return 0
    fi
}
complete -F _muttlike_imap muttlike-imap
"""

FISH = r"""# Fish completion for muttlike-imap.
# Install via:  muttlike-imap --completion fish | source
# Or save to ~/.config/fish/completions/muttlike-imap.fish

complete -c muttlike-imap -l limit -x -d 'Maximum number of results (default 10)'
complete -c muttlike-imap -l mailbox -x -d 'IMAP folder to search (default INBOX)'
complete -c muttlike-imap -l summary -d 'Human-readable output instead of JSON'
complete -c muttlike-imap -l body -d 'Include full body text in output'
complete -c muttlike-imap -l uid -x -d 'Fetch specific messages by UID instead of searching'
complete -c muttlike-imap -l list-mailboxes -d 'List available IMAP folders and exit'
complete -c muttlike-imap -l me -x -d 'Email address used by ~p / ~P'
complete -c muttlike-imap -l imap-host -x -d 'IMAP server host'
complete -c muttlike-imap -l imap-port -x -d 'IMAP server port (default 993)'
complete -c muttlike-imap -l imap-user -x -d 'IMAP username'
complete -c muttlike-imap -l imap-password-env -x -d 'Read password from this env var'
complete -c muttlike-imap -l imap-password-cmd -x -d 'Shell command that prints the password'
complete -c muttlike-imap -l imap-tls -x -a 'true false' -d 'Use TLS'
complete -c muttlike-imap -l config -r -d 'Path to a config file'
complete -c muttlike-imap -l timeout -x -d 'Socket timeout in seconds'
complete -c muttlike-imap -l completion -x -a 'bash zsh fish' -d 'Print a shell completion script'
complete -c muttlike-imap -l version -d 'Show version and exit'
complete -c muttlike-imap -s h -l help -d 'Show help and exit'
"""

SCRIPTS = {"zsh": ZSH, "bash": BASH, "fish": FISH}


def get_completion(shell: str) -> str:
    """Return the completion script for ``shell``. Raises ValueError if unknown."""
    try:
        return SCRIPTS[shell]
    except KeyError as e:
        raise ValueError(
            f"unknown shell {shell!r}; choose one of {', '.join(sorted(SCRIPTS))}"
        ) from e
